export const HOMEPAGE = '/'
export const LOGIN = '/login'
export const REGISTER = '/register'
export const RECORD = '/record'
export const INSPECTOR = '/inspector'
export const BUSINESS = '/business'
