export * from './form'
export * from './layout'
export * from './record'
export * from './table'

export * from './ButtonC'
export * from './table/TableGuide'
export * from './product/ProductStatic'
export * from './product/ProductList'
export * from './product/ProductInfo'
export * from './TagCurrent'
export * from './Timeline'
export * from './BackTopC'
export * from './modal/CreateProductModal'
export * from './modal/InfoProductModal'
export * from './modal/HomepageModal'
