export const HOMEPAGE = '/'
export const LOGIN = '/login'
export const REGISTER = '/register'
export const HR = '/hr'
export const PROMOTION = '/promotion'
export const INSPECTOR = '/inspector'
export const BUSINESS = '/business'
